### PR TITLE
udfinfo: Replace data type `off_t` with `loff_t`

### PR DESCRIPTION
**Pull request by Johnson-zs**
The udfinfo cannot work When the capacity of the disc is too large (assuming the 4.7G specification). So use `loff_t` to make it work.

**Reference this kernel patch**: http://lkml.iu.edu/hypermail/linux/kernel/2101.1/06214.html

### CODE REVIEW

**Comment by pali** [comment]
Why? `off_t` should be here 64bit large, and so should be able to handle larger files than 4.7G.

**Comment by Johnson-zs** [comment]
In my environment off_t is a long int type (32-bit),  my compiler version is gcc 8.3.0.

I looked up the definition of off_t: 
```
#if defined __USE_UNIX98 || defined __USE_XOPEN2K
# ifndef __off_t_defined
# ifndef __USE_FILE_OFFSET64
typedef __off_t off_t;
# else
typedef __off64_t off_t;
# endif
# define __off_t_defined
# endif
# if defined __USE_LARGEFILE64 && !defined __off64_t_defined
typedef __off64_t off64_t;
# define __off64_t_defined
# endif
#endif
```
`off_t` is 32-bit by default in my environment ( set a macro definition at compile time to be 64-bit if need 64-bit).
So changing `off_t` to `loff_t` will ensure that it will always be 64-bit.

**Comment by Johnson-zs** [comment]
> Why? `off_t` should be here 64bit large, and so should be able to handle larger files than 4.7G.

In my environment `off_t` is a long int type (32-bit),  my compiler version is gcc 8.3.0.

I looked up the definition of `off_t`: 
```
#if defined __USE_UNIX98 || defined __USE_XOPEN2K
# ifndef __off_t_defined
# ifndef __USE_FILE_OFFSET64
typedef __off_t off_t;
# else
typedef __off64_t off_t;
# endif
# define __off_t_defined
# endif
# if defined __USE_LARGEFILE64 && !defined __off64_t_defined
typedef __off64_t off64_t;
# define __off64_t_defined
# endif
#endif
```
`off_t` is 32-bit by default in my environment ( set a macro definition at compile time to be 64-bit if need 64-bit).
So changing `off_t` to `loff_t` will ensure that it will always be 64-bit.

**Comment by pali** [comment]
Could you check that udfinfo compiled by udftools build system really has this problem?

**Comment by Johnson-zs** [comment]
I'm using the wrong debugging method.

**Pull request closed without merging**
