### PR TITLE
License and spelling fixes

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Comment by pali** [comment]
Files ecma_167.h and osta_udf.h are manually synced with Linux kernel. If you are doing changes in these files, please send patches to Linux kernel.

**Comment by a1346054** [comment]
Thank you for spotting that, rebased now without any changes to those files.

**Comment by pali** [comment]
Ok, I will let this pull request open until changes are merged into Linux kernel. Please send then links to patches or included commits.

**Comment by a1346054** [comment]
I dropped the commit that removes trailing whitespace, reworded commit messages to be in line with rest of repository, and added a few more typo fixes.

**Comment by pali** [comment]
So as I wrote year ago, please show git commits in linux kernel with those changes or links to sent patches in mailinglists/patchworks. After those changes lands in linux kernel I will include them also into udftools.

**Comment by a1346054** [comment]
None of the affected files are part of the linux kernel git repositories, unless I'm missing something.

**Comment by pali** [comment]
So then, please fix it. Thanks.

**Comment by a1346054** [comment]
https://www.kernel.org/doc/html/latest/filesystems/udf.html says that the toolset is on https://github.com/pali/udftools and hence is not part of the linux kernel.

I've looked in fs/udf in the kernel tree, as well as elsewhere, and none of the following files are in there:
```
NEWS
libudffs/extent.c
mkudffs/file.c
udfinfo/readdisc.c
udflabel/main.c
wrudf/ide-pc.h
wrudf/wrudf-cdr.c
wrudf/wrudf-cmnd.c
wrudf/wrudf.c
```
Those are the only files I've fixed typos in.

I am therefore very lost regarding what you wish me to change or submit to the linux kernel, please advise.

**Comment by pali** [comment]
You have modified files ecma_167.h and osta_udf.h and I have already wrote in second comment that these files are synced between linux kernel and udftools project. So please first send changes for those files to linux kernel and after they are merged and I will come back to review this pull request.

**Comment by a1346054** [comment]
Those files are not modified.

**Comment by pali** [comment]
So what have you done with this pull request and those changes? You asked me for merging changes for ecma_167.h, osta_udf.h and other files. Then I have wrote to you that those two files are in sync with linux and what needs to be done. And now are you writing me that you have not modified them. Are you kidding me? I really do not have more time for this discussion. Clear instructions are there already.

**Comment by pali** [comment]
Closing due to submitter inactivity.

**Comment by wdlkmpx** [comment]
a1346054 is right, ecma_167.h and osta_udf.h are not modified in the latest PR commit, this is some sort of aggression towards anonymous people

**Comment by pali** [comment]
Yes, this project is not anonymous, it is used on lot of linux distributions, some code is shared with linux kernel and maintainer has responsibility for it.

**Pull request closed without merging**
